# Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:

# 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

# By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.

def even_fibonacci(num)
  array = [1, 2]
  even_fibs = [2]
  while array[-1] <= num
    array << array[-1] + array[-2]
    if array[-1].even?
      even_fibs << array[-1]
    end
  end
  even_fibs.reduce(:+)
end

p even_fibonacci(4000000)